### ISSUE TITLE
FatalErrorException when submitting a form.

### ISSUE THREAD

**Issue by davidsoderberg** [laracasts/Integrated#21]
I get 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method ErrorException::getStatusCode()' when I try to submit a form why?

This is my code:

```
$this->visit('login')
->type('david', 'loginUsername')
->type('password', 'loginpassword')
->press('Login')
->see('You have logged in.');
```

**Comment by JeffreyWay** [comment]
Which extension are you using? Laravel?

Also, when you try it manually in the browser, does it work?

**Comment by davidsoderberg** [comment]
Laravel and yes it works in browser...

**Comment by JeffreyWay** [comment]
Hmm - with a fresh install, I'm getting green.

Can you pinpoint where the error is occurring on your end? You can add ->dump() anywhere within your test to spit out the current response content.

Also, make sure that you've done a `composer update` for this package in the last few days.

**Comment by davidsoderberg** [comment]
It is when it press the button its gives the error and I have updated the package today also.

**Comment by davidsoderberg** [comment]
Here is stack trace:

```
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method ErrorException::getStatusCode()' in C:\Users\david\Deskto
p\codeblock\app\Exceptions\Handler.php:45
Stack trace:
#0 C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExc
eptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method ErrorException::getStatusCode()' in C:\Users\david\Desktop\c
odeblock\app\Exceptions\Handler.php:45
Stack trace:
#0 C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExc
eptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method ErrorException::getStatusCode()' in C:\Users\david\Desktop\c
odeblock\app\Exceptions\Handler.php:45
Stack trace:
#0 C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExc
eptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method ErrorException::getStatusCode()' in C:\Users\david\Desktop\c
odeblock\app\Exceptions\Handler.php:45
Stack trace:
#0 C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\HandleExceptions.php(116): Illuminate\Foundation\Bootstrap\HandleExc
eptions->fatalExceptionFromError(Array)
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#2 {main}

Fatal error: Call to undefined method ErrorException::getStatusCode() in C:\Users\david\Desktop\codeblock\app\Exceptions\Handler.php on line 45

Call Stack:
    0.0003     125720   1. {main}() C:\xampp\php\phpunit:0
    0.0130     361192   2. PHPUnit_TextUI_Command::main() C:\xampp\php\phpunit:46
    0.0130     364400   3. PHPUnit_TextUI_Command->run() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:129
    0.0988    3096688   4. PHPUnit_TextUI_TestRunner->doRun() C:\xampp\php\pear\PHPUnit\TextUI\Command.php:176
    0.1092    3341728   5. PHPUnit_Framework_TestSuite->run() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:388
    0.1108    3352064   6. PHPUnit_Framework_TestSuite->run() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestSuite.php:716
    0.1110    3353416   7. PHPUnit_Framework_TestSuite->run() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestSuite.php:716
    1.3003   14774872   8. PHPUnit_Framework_TestCase->run() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestSuite.php:716
    1.3003   14774840   9. PHPUnit_Framework_TestResult->run() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestCase.php:687
    1.3003   14775360  10. PHPUnit_Framework_TestCase->runBare() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestResult.php:609
    1.4922   15293360  11. PHPUnit_Framework_TestCase->runTest() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestCase.php:731
    1.4923   15293848  12. ReflectionMethod->invokeArgs() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestCase.php:846
    1.4923   15293864  13. MenuControllerTest->testLoginPage() C:\Users\david\Desktop\codeblock\vendor\phpunit\phpunit\src\Framework\TestCase.php:846
    1.6142   16030064  14. Laracasts\Integrated\Extensions\Laravel->press() C:\Users\david\Desktop\codeblock\tests\integration\MenuControllerTest.php:22
    1.6142   16030088  15. Laracasts\Integrated\Extensions\Laravel->submitForm() C:\Users\david\Desktop\codeblock\vendor\laracasts\integrated\src\Extensions\Integrat
ionTrait.php:273
    1.6221   16181848  16. Laracasts\Integrated\Extensions\Laravel->makeRequestUsingForm() C:\Users\david\Desktop\codeblock\vendor\laracasts\integrated\src\Extension
s\Laravel.php:46
    1.6222   16182776  17. Laracasts\Integrated\Extensions\Laravel->makeRequest() C:\Users\david\Desktop\codeblock\vendor\laracasts\integrated\src\Extensions\Laravel
.php:99
    1.6222   16182776  18. Illuminate\Foundation\Testing\TestCase->call() C:\Users\david\Desktop\codeblock\vendor\laracasts\integrated\src\Extensions\Laravel.php:61
    1.6225   16188656  19. Illuminate\Foundation\Http\Kernel->handle() C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Testing\Ap
plicationTrait.php:50
    1.6418   16340432  20. Illuminate\Foundation\Http\Kernel->renderException() C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\H
ttp\Kernel.php:89
    1.6418   16340456  21. App\Exceptions\Handler->render() C:\Users\david\Desktop\codeblock\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php:191

```

**Comment by davidsoderberg** [comment]
@JeffreyWay I don't know if this makes it easier for you to error searching I use illuminate/html for forms could that be why I got this errors?

**Comment by davidsoderberg** [comment]
Could it have some connect to that I use the artisan server?

**Comment by davidsoderberg** [comment]
Sovled when I got vhost to work :smile:

**Comment by rephiscorth** [comment]
@davidsoderberg how did you solve this?
